### PR TITLE
Add slogan to logos, fix readme CC link

### PR DESCRIPTION
**Pull request by felix-hilden**
Aye, back at it! Here's a suggestion for adding the slogan. I opted for a gray color, since outlining with a thick white border didn't look as good with the smaller text. Plus, I think having the slogan in less contrast could be a nice touch in itself. I also gave it a bit more breathing room around the edges.

Hope the -[ ]- was not essential 😅

Here's what they look like:
beartype-white
beartype-gray
beartype-black

### CODE REVIEW

**Comment by leycec** [comment]
**This is hot af.** I'm no Zoomer, but I'm pretty sure that means they're hot.

I was *just* about to set one of the current banners as our [GitHub social media preview](https://docs.github.com/en/github/administering-a-repository/customizing-your-repositorys-social-media-preview). But now I learn the multiple virtues of ~~laziness~~ patience, because these dominate those like a desperate bear dominates the salmon run.

I of course approve and congratulate you on your continued dominance of the art world. If you have infinite time beyond all conception of time, would re-rendering the slogan text in an alternate font face – say, maybe either [the wide or narrow font face used in your original pro-safety banners](https://github.com/beartype/beartype/issues/8#issuecomment-761527746) – be feasible for that added *pop*? If not, that's, like, totally cool too, you know, man.

In my mind's eye, you are [Bob Ross](https://www.youtube.com/user/BobRossInc) with an even larger and more unwieldy afro, fashionable blond Scandinavian hair, and five Wacom tablets strapped together into the largest digital easel available on the European continent.

**Comment by felix-hilden** [comment]
Here's the narrow font! You're right, having a different font does look nice 😄 Now I think my next logical step is to phone up Louvre 😜 But seriously though I appreciate it, my bear friend! Happy to help 👍

**Comment by leycec** [comment]
Drunken Soviet-era war bear roars... *with approval!*

In Mother Russia, war bears ride you.

What the war bear is trying to say is, this is Louvre-worthy. Please feel free to merge this as you please. You now have the conn.

**Comment by leycec** [comment]
Another masterful critique of the post-modern art landscape. Thanks so much for these contributions that are both objectively *and* literally amazing, Felix.

I now insist you binge the brutal martial arts series of your choice. Might I recommend [Gareth Huw Evans' seminal Indonesian masterpiece *Serbuan Maut* (*The Raid*)](https://www.youtube.com/watch?v=m6Q7KnXpNOg), because nothing says "tropical bloodsport that momentarily makes me forget one-third of my nation overlaps the Arctic circle" like [silat](https://en.wikipedia.org/wiki/Silat#Training).

**Comment by felix-hilden** [comment]
You're most welcome! Oh, not really my cup of tea, besides the occasional single punch that is enough or a set of extremely, nay, impossibly rapid punches accompanied by a primal roar 😅 I guess that's martial arts too. But the trailer looked cool, I'll give you that!

Looking forward to seeing the library grow! Perhaps I'll drop in again once I've actually figured out [what *Beartype* does](https://www.reddit.com/r/Python/comments/k7z1f8/i_just_made_the_worlds_first_o1_runtime_type/gevrgjy?utm_source=share&utm_medium=web2x&context=3) 😄 Also, I'll save the logo project files deep in my hard drive, so feel free to ping me and ask for changes if needed!

**Comment by leycec** [comment]
> a set of extremely, nay, impossibly rapid punches accompanied by a primal roar

This accurate description of Asian media made me immediately want to rewatch [*Hakuto no Ken* (*Fist of the North Star*)](https://www.youtube.com/watch?v=C_HYGYeAj38), which I then did with nostalgic tears of joy. I have no regrets.

> Perhaps I'll drop in again once I've actually figured out what Beartype does...

**...everything.** It does literally everything, Felix.

If `beartype` doesn't swell your six pack to grotesque Conan-like proportions, accelerate your memory retention and basic cognition to a frightening plateau matched only by NSA-funded quantum computers running Gentoo Linux, *and* augment your sex life beyond that hitherto unknown to mortal man, you are naturally entitled to a full refund.

> Also, I'll save the logo project files deep in my hard drive, so feel free to ping me and ask for changes if needed!

Thanks so much for this and everything, Felix. If we never meet again on this side of the Sun, may all your earthly days on [our Pale Blue Dot](https://www.youtube.com/watch?v=mmcc6HL9Ekk) be fruitful and full of childlike wonderment. You and @harens deserve all the best.

**Comment by leycec** [comment]
@felix-hilden: Actually, not to be anti-climactic, but... **I have one final request.** Don't worry! It's mostly painless. Would I lie?

It saddened me that my writing is so bad that the amazing computer vision guy who is smarter than me and branded my own Python package still has no idea what that package does or why or when he should ever use it. So, [I wrote a FAQ](https://github.com/beartype/beartype#faq).

Would you mind critiquing that? Specifically, does [that FAQ](https://github.com/beartype/beartype#faq) answer your burning desire to know *what* `beartype` actually does, *why* you would actually use `beartype`, and *when* you would actually use `beartype`?

If not, I'll just call off the rest of 2021 and burn my devbox in a toxic plastic slagheap on the front lawn. My wife will be displeased, but sometimes you just gotta.

**Comment by felix-hilden** [comment]
Wow, that's positively amazing! I thought it would be a tl;dr, but it was something better: an explanation. Especially the "when" and "what" sections 👍 That's some seriously good text! I actually don't know if there's anything worth changing, at most you could possibly have a condensed version of it in the tl;dr that we already have for those that understand the lingo right away. Maybe something like: Beartype is a minimal O(1) type checker that performs one-way random walks for nested containers to check the type of each argument (see faq/timings/...).

Awesome, man! 😄

**Comment by leycec** [comment]
**Aww.** Beartype devs the best devs.

> ...you could possibly have a condensed version of it in the tl;dr that we already have for those that understand the lingo right away.

That's... *a really good idea.* Sadly, I am lazy and tired. I should have done what you suggested. Instead, I just suffixed the most reprehensibly jargon-polluted sentence of any introduction ever with a shoddy link to our FAQ: <sup>**bolded** below for emphasis</sup>

> Beartype brings Rust- and C++-inspired zero-cost abstractions into the lawless world of dynamically-typed Python by enforcing type safety at the granular level of functions and methods against type hints standardized by the Python community in O(1) non-amortized worst-case time with negligible constant factors. **If the prior sentence was unreadable jargon, [see our friendly and approachable FAQ for a human-readable synopsis.](https://github.com/beartype/beartype#frequently-asked-questions-faq)**

*Yeah.* That's alot better. I mean, it's still too much jargon and makes my eyes squint. But at least we soften the blow with something a human can actually read. Mission accomplished, northerly men.

Thanks yet again for the relentless outpouring of good feels, hot branding, and Sphinx structure, Felix. I'm pushing out `beartype 0.5.2` either tonight or tomorrow night in honour of everyone's magisterial contributions. :crown: 

Have a warm rest of your Winter! May we all be vaccinated before 2032.

**Comment by felix-hilden** [comment]
😄 I already read the "before 2032" version on my email, but that could be a more appropriate estimate... You're most welcome, and thank *you* for being an awesome author and your encouragement!

**Pull request merged**
